# Generated by Django 3.2.16 on 2022-12-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='picture',
        ),
    ]
