# Generated by Django 3.2.16 on 2022-12-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_rename_photo_person_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birt_date',
            new_name='birth_date',
        ),
    ]
